apiVersion: v1
kind: Service
metadata:
  name: dep-service1
  labels:
    app: mediawiki
spec:
  # ports:
  # - port: 80
  #   targetPort: 80
  #   protocol: TCP
  # selector:
  #   app: mediawiki
  type: NodePort
  selector:
    app: mediawiki
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000