apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment1
  labels:
    app: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: testmediawiki
        image: test:1.1
        ports:
        - containerPort: 80
