apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-helm
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: {{ .Values.image}}
        ports:
        - containerPort: {{ .Values.containerPort}}