apiVersion: v1
kind: Service
metadata:
  name: dep-service-helm
  labels:
    app: {{ .Values.appName }}
spec:
  # ports:
  # - port: 80
  #   targetPort: 80
  #   protocol: TCP
  # selector:
  #   app: mediawiki
  type: NodePort # ClusterIP when deploying on AKS
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.targetPort }}
      
      nodePort: 30002